import { google } from '@ai-sdk/google';
import { generateObject } from 'ai';
import { z } from 'zod';

export interface DamageAnalysis {
  hasDamage: boolean;
  severity: 'none' | 'minor' | 'moderate' | 'severe';
  damageDescription: string;
  isSyntheticImage: boolean;
  syntheticConfidence: number; // 0-100
  suspiciousFlags: string[];
  recommendation: string;
  trustScore: number; // 0-100
}

const damageAnalysisSchema = z.object({
  hasDamage: z.boolean().describe('Whether the image shows any damage to the product'),
  severity: z.enum(['none', 'minor', 'moderate', 'severe']).describe('Severity of damage if present'),
  damageDescription: z.string().describe('Detailed description of the damage visible'),
  damageType: z.string().describe('Type of damage (e.g., broken, torn, scratched, dented, water damage)'),
  affectedAreas: z.array(z.string()).describe('Areas of the product affected by damage'),
  estimatedRepairCost: z.string().describe('Rough estimate of repair or replacement cost impact'),
});

const syntheticDetectionSchema = z.object({
  isSynthetic: z.boolean().describe('Whether the image appears to be AI-generated or synthetic'),
  confidence: z.number().min(0).max(100).describe('Confidence level (0-100) that image is synthetic'),
  indicators: z.array(z.string()).describe('Specific indicators suggesting synthetic origin'),
  realismScore: z.number().min(0).max(100).describe('How realistic the image appears (0=clearly fake, 100=very realistic)'),
});

export async function analyzeImageForDamage(imageBase64: string): Promise<DamageAnalysis> {
  try {
    // FIRST: Check for SynthID watermark (Google's official AI detection)
    const synthIdCheck = await generateObject({
      model: google('gemini-2.0-flash-exp'),
      schema: z.object({
        hasSynthIdWatermark: z.boolean().describe('Whether this image contains a SynthID watermark indicating it was generated by Google AI'),
        synthIdConfidence: z.number().min(0).max(100).describe('Confidence that SynthID watermark is present'),
        generatedBy: z.string().describe('If SynthID detected, which Google AI tool generated it (Imagen, etc.)'),
      }),
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: `CRITICAL: Check if this image contains a SynthID watermark.

SynthID is Google's official watermarking technology for AI-generated content. Images created by Google AI tools (Imagen, Gemini image generation, etc.) have invisible SynthID watermarks embedded.

Your task:
1. Scan this image for the presence of a SynthID watermark
2. If detected, identify which Google AI tool created it
3. Provide your confidence level (0-100%)

Note: SynthID watermarks are invisible to humans but detectable by AI systems like you. They persist through modifications like cropping, filters, and compression.

If you detect ANY indication this was generated by Google AI tools, report it immediately with HIGH confidence.`,
            },
            {
              type: 'image',
              image: imageBase64,
            },
          ],
        },
      ],
    });

    console.log('[SYNTHID CHECK]:', {
      hasSynthIdWatermark: synthIdCheck.object.hasSynthIdWatermark,
      confidence: synthIdCheck.object.synthIdConfidence,
      generatedBy: synthIdCheck.object.generatedBy,
    });

    // Analyze for damage
    const damageAnalysis = await generateObject({
      model: google('gemini-2.0-flash-exp'), // Using latest vision model
      schema: damageAnalysisSchema,
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: `You are an expert damage assessment specialist. Analyze this product image for any signs of damage, defects, or issues.

Look for:
- Physical damage (cracks, breaks, dents, scratches)
- Water damage or staining
- Missing parts or components
- Deformation or warping
- Color fading or discoloration
- Assembly issues or misalignment

Provide a thorough assessment with specific details about what you observe.`,
            },
            {
              type: 'image',
              image: imageBase64,
            },
          ],
        },
      ],
    });

    // Detect synthetic/AI-generated images
    const syntheticAnalysis = await generateObject({
      model: google('gemini-2.0-flash-exp'),
      schema: syntheticDetectionSchema,
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: `You are a HIGHLY TRAINED forensic image analyst specializing in detecting AI-generated and synthetic images. Your job is to be EXTREMELY THOROUGH and SKEPTICAL.

CRITICAL: Be VERY aggressive in detecting AI-generated content. Even subtle hints should raise red flags.

Analyze this image with MAXIMUM SCRUTINY for these AI generation indicators:

🤖 DALL-E / Midjourney / Stable Diffusion Signatures:
- Overly smooth or "painted" texture quality
- Perfect symmetry where it shouldn't exist
- Unnatural bokeh or background blur
- "Dreamy" or artistic rendering style
- Impossibly perfect lighting
- Stock photo aesthetic with no imperfections

🚩 Technical AI Artifacts:
- Blurred or warped text/logos
- Inconsistent object shadows
- Warped edges or melting features
- Repeated patterns that are too uniform
- Unnatural color gradients
- Strange reflections or highlights
- Impossible perspectives or angles
- Objects that blend unnaturally into backgrounds

📸 Real Photo Indicators (Look for ABSENCE of these):
- Natural grain or noise
- Lens flare or chromatic aberration
- Motion blur in expected places
- Authentic wear and tear
- Real-world imperfections
- Natural lighting inconsistencies
- EXIF metadata traces
- Realistic depth of field

⚠️ Photoshop/Manipulation Signs:
- Clone stamp patterns
- Mismatched lighting between elements
- Edge halos around objects
- Inconsistent compression artifacts
- Color banding in gradients

BE SUSPICIOUS if the image looks "too perfect" or "too clean". Real product damage photos have authentic imperfections, dust, fingerprints, natural lighting variations.

Rate your confidence HIGH (70-100%) if you see ANY clear AI indicators. Rate MEDIUM (40-69%) if suspicious. Rate LOW (0-39%) only if clearly authentic photography.`,
            },
            {
              type: 'image',
              image: imageBase64,
            },
          ],
        },
      ],
    });

    // Identify suspicious flags
    const suspiciousFlags: string[] = [];
    
    // CRITICAL: Check SynthID first (most authoritative)
    if (synthIdCheck.object.hasSynthIdWatermark) {
      suspiciousFlags.push(`🚨 SYNTHID WATERMARK DETECTED - Generated by ${synthIdCheck.object.generatedBy}`);
      suspiciousFlags.push(`🤖 Google AI-generated image confirmed (${synthIdCheck.object.synthIdConfidence}% confidence)`);
      suspiciousFlags.push('⛔ AUTOMATIC REJECTION - This is definitively NOT a real photograph');
    }
    
    console.log('[VISION DEBUG] SynthID Check:', {
      hasSynthIdWatermark: synthIdCheck.object.hasSynthIdWatermark,
      synthIdConfidence: synthIdCheck.object.synthIdConfidence,
      generatedBy: synthIdCheck.object.generatedBy,
    });

    console.log('[VISION DEBUG] Synthetic Analysis:', {
      isSynthetic: syntheticAnalysis.object.isSynthetic,
      confidence: syntheticAnalysis.object.confidence,
      realismScore: syntheticAnalysis.object.realismScore,
      indicators: syntheticAnalysis.object.indicators,
    });

    console.log('[VISION DEBUG] Damage Analysis:', {
      hasDamage: damageAnalysis.object.severity !== 'none',
      severity: damageAnalysis.object.severity,
      type: damageAnalysis.object.damageType,
    });
    
    // Flag if confidence is above 50% (being more aggressive)
    if (syntheticAnalysis.object.confidence > 50) {
      suspiciousFlags.push(`⚠️ Image appears to be AI-generated (${syntheticAnalysis.object.confidence}% confidence)`);
      if (syntheticAnalysis.object.confidence > 75) {
        suspiciousFlags.push('🚩 HIGH confidence this is NOT a real photograph');
      }
    }

    // Add specific indicators found
    if (syntheticAnalysis.object.indicators.length > 0) {
      syntheticAnalysis.object.indicators.forEach(indicator => {
        suspiciousFlags.push(`🔍 ${indicator}`);
      });
    }

    // Flag suspicious combinations
    if (damageAnalysis.object.severity === 'none' && syntheticAnalysis.object.confidence > 40) {
      suspiciousFlags.push('⚠️ AI-generated image with no visible damage - LIKELY FRAUDULENT CLAIM');
    }

    if (damageAnalysis.object.severity === 'severe' && syntheticAnalysis.object.realismScore < 60) {
      suspiciousFlags.push('🚩 Severe damage claimed but image appears artificial');
    }

    if (syntheticAnalysis.object.realismScore < 50 && syntheticAnalysis.object.confidence > 60) {
      suspiciousFlags.push('🚨 Low realism score + high AI confidence = SYNTHETIC IMAGE');
    }

    // Calculate trust score (0-100, higher = more trustworthy)
    let trustScore = 100;
    
    // CRITICAL: SynthID detection = immediate zero trust
    if (synthIdCheck.object.hasSynthIdWatermark) {
      trustScore = 0; // Definitive proof of AI generation
    } else {
      // Aggressive deduction for synthetic detection
      if (syntheticAnalysis.object.confidence > 50) {
        trustScore -= syntheticAnalysis.object.confidence;
      }

      // Penalize low realism scores
      if (syntheticAnalysis.object.realismScore < 70) {
        trustScore -= (70 - syntheticAnalysis.object.realismScore);
      }

      // Reduce for unlikely damage scenarios
      if (damageAnalysis.object.severity === 'none') {
        trustScore -= 20; // No damage visible in return request
      }
    }

    trustScore = Math.max(0, Math.min(100, trustScore));

    // Build recommendation (SynthID takes absolute priority)
    let recommendation = '';
    if (synthIdCheck.object.hasSynthIdWatermark) {
      recommendation = `⛔ IMMEDIATE REJECTION - SynthID watermark detected. Image generated by ${synthIdCheck.object.generatedBy}. This is DEFINITIVE PROOF of AI generation. FRAUD ATTEMPT.`;
    } else if (syntheticAnalysis.object.confidence > 60) {
      recommendation = '🚨 REJECT - Image appears to be AI-generated or synthetic. REQUIRE AUTHENTIC PHOTO.';
    } else if (trustScore < 40) {
      recommendation = '🚩 REJECT - Multiple red flags detected. Manual verification required.';
    } else if (syntheticAnalysis.object.confidence > 40 && damageAnalysis.object.severity === 'none') {
      recommendation = '⚠️ REJECT - Suspicious image with no damage. Likely fraudulent claim.';
    } else if (damageAnalysis.object.severity === 'severe' && trustScore > 60) {
      recommendation = '✅ APPROVE - Significant damage documented in authentic photo. Process refund.';
    } else if (damageAnalysis.object.severity === 'moderate' && trustScore > 50) {
      recommendation = '💬 REVIEW - Moderate damage. Offer repair credit or partial refund.';
    } else if (damageAnalysis.object.severity === 'minor' && trustScore > 50) {
      recommendation = '💬 REVIEW - Minor damage. Offer store credit or discount.';
    } else if (damageAnalysis.object.severity === 'none') {
      recommendation = '❌ REJECT - No visible damage in image. Clarify return reason.';
    } else {
      recommendation = '⚠️ MANUAL REVIEW - Trust score too low for automatic decision.';
    }

    return {
      hasDamage: damageAnalysis.object.severity !== 'none',
      severity: damageAnalysis.object.severity,
      damageDescription: `${damageAnalysis.object.damageDescription}\n\nDamage Type: ${damageAnalysis.object.damageType}\nAffected Areas: ${damageAnalysis.object.affectedAreas.join(', ')}\nRepair Cost Impact: ${damageAnalysis.object.estimatedRepairCost}`,
      isSyntheticImage: syntheticAnalysis.object.isSynthetic,
      syntheticConfidence: syntheticAnalysis.object.confidence,
      suspiciousFlags,
      recommendation,
      trustScore,
    };
  } catch (error) {
    console.error('Error analyzing image:', error);
    return {
      hasDamage: false,
      severity: 'none',
      damageDescription: 'Unable to analyze image',
      isSyntheticImage: false,
      syntheticConfidence: 0,
      suspiciousFlags: ['Error analyzing image - manual review required'],
      recommendation: '⚠️ Unable to analyze image. Please contact support.',
      trustScore: 0,
    };
  }
}
